version: '3.8'

services:

  # Frontend service configuration
  frontend:
    image: node:latest
    container_name: pacmail-frontend
    working_dir: /frontend
    restart: always
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL} # API URL for the frontend to communicate with the backend
    depends_on:
      - backend
      - database
    volumes:
      - ./frontend:/frontend
    command: npm start
    network_mode: host  
  
  # Backend service configuration
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pacmail-backend
    hostname: backend
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      - database
    volumes:
      - ./backend:/backend
    network_mode: host
  
  # Database service configuration
  database:
    image: postgres:13
    container_name: pacmail-database
    hostname: database
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    network_mode: host

# Volume for database service (PostgreSQL data)
volumes:
  postgres_data:
    name: postgres_data