# Define name of the workflow
name: Build and Testing - CI

# Set up workflow trigger
# In this workflow I set the trigger on pull request to the main branch
# It means, this workflow will run if there is a pull request to the main branch
on:
  pull_request:
    branches: [ "main"] 

# Set up the workflow job
jobs:
  build-and-tesing:
    name: Build and Testing # define name of the job
    environment: production # Specify the environment for the job (Set up the environment in the repo's settings)
    runs-on: ubuntu-latest  # Define the runner to execute the job

    # Set up steps when running the job
    steps: 

      # Check out the repository code using the selected 'uses'
      - name: Checkout repository
        uses: actions/checkout@v2
      
      # Set up Python version 3.10 for the backend using the selected 'uses'
      - name: Set up python for backend
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
        
      # Install backend dependencies
      - name: Install backend dependencies
        run: |
  
            python -m pip install --upgrade pip
            pip install -r testing/requirements.txt

      # Create .env file in the container
      - name: Create .env file
        run: |
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" > .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env 

      # Build and start containers in the background
      - name: Run Docker Compose
        run: |
          
            docker-compose up --build --detach
      
      # Run testing file using pytest
      - name: Build and Test backend
        run: | 
    
            pytest testing/test_signup.py